baseURL = 'https://swkwien.github.io/GDCR2021/'
languageCode = 'en-us'
title = 'Global Day of Coderetreat 2021 by swkWien at Nagarro'
description = "A day of deliberate practice and learning"
theme = "reveal-hugo"

[params]
custom_css = ["css/custom.css"]

[author]
name = "Claus Aichinger, Peter Kofler, Paul Rohorzka, Rea Sutter, Adam Zielinksi"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
